#!/usr/bin/env bash

usage() {
  echo "plotjuggler_download [--version <version>]"
}

VERSION=3.17.1

while [[ $# -gt 0 ]]; do
  case $1 in
    --version)
      VERSION=$2
      shift 2;
      ;;
    *)
      shift 1;
      ;;
  esac
done

filename="PlotJuggler-$VERSION-x86_64.AppImage"
url="https://github.com/PlotJuggler/PlotJuggler/releases/download/${VERSION}/${filename}"

plotjuggler_dir="${HOME}/.local/bin/PlotJuggler"
mkdir -p "${plotjuggler_dir}"
plotjuggler_exe="${plotjuggler_dir}/${filename}"
curl -sL -o "${plotjuggler_exe}" ${url}
plotjuggler_symlink_versioned="${HOME}/.local/bin/plotjuggler-${VERSION}"
ln -s ${plotjuggler_exe} ${plotjuggler_symlink_versioned}
plotjuggler_symlink="${HOME}/.local/bin/plotjuggler"
rm -f "${plotjuggler_symlink}"
ln -s ${plotjuggler_exe} "${plotjuggler_symlink}"
chmod +x "${plotjuggler_symlink}"

