#!/usr/bin/env bash

if [[ $# -ge 1 ]]; then
    selected=$1
    if [[ $# -eq 2 ]]; then
        selected_name_override=$2
    fi
else
    selected=$(find ~/repos -maxdepth 5 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

if [[ "$selected" == */.worktrees/* ]]; then
    repo_name=$(basename "$(dirname "$(dirname "$selected")")" | tr . _)
    branch_name=$(basename "$selected" | tr . _)
    selected_name_evaluated="${repo_name}--${branch_name}"
else
    selected_name_evaluated=$(basename "$selected" | tr . _)
fi
selected_name="${selected_name_override:-${selected_name_evaluated}}"
tmux_running=$(pgrep tmux)

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t $1
    else
        tmux switch-client -t $1
    fi
}

switch_to $selected_name
